// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufrgzeclafskowahyxjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmcmd6ZWNsYWZza293YWh5eGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTQwOTIsImV4cCI6MjA2NTQ5MDA5Mn0.Qy3i-AtnhyD9CfYBb5WRMEBbI4_83Z7YYdgHhHCgy1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);